import type { Metadata } from "next";
import { Geist, Geist_Mono, Tektur } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const tektur = Tektur({
  subsets: ["latin"], // Specify the subsets you need (e.g., 'latin', 'cyrillic', etc.)
  display: "swap", // This ensures text is visible while the font is loading
  variable: "--font-tektur", // Optional: Define a CSS variable for easier use with Tailwind CSS
  weight: ["400", "700", "900"], // Specify the weights you plan to use
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${tektur.className} ${tektur.variable} antialiased h-screen w-screen overflow-x-hidden`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
